# config/routes.yml

home:
  path: /
  defaults: { _controller: 'API\APIController::home' }

api_1:
  prefix: /drupalci/api/1
  resource: routes/1.yml

api_1:
  prefix: /drupalci/api/mock
  resource: routes/mock.yml
